### ISSUE TITLE
Error: Could not set mapnik version to 3.0.0

### ISSUE THREAD

**Issue by willwhite** [mapbox/tilemill#2462]
Occurs on master branch. Appears to be related to [this commit](https://github.com/mapbox/carto/commit/93fbc89649cf5a918ccfc1349dc7404c4733c757) and the new release of carto.

```
[tilemill] /Users/willwhite/tilemill/commands/core.bones:102
[tilemill]         throw new Error("Could not set mapnik version to " + mapnik.versions.m
[tilemill]               ^
[tilemill] Error: Could not set mapnik version to 3.0.0
[tilemill]     at command.bootstrap (/Users/willwhite/tilemill/commands/core.bones:102:15)
[tilemill]     at Command (/Users/willwhite/tilemill/node_modules/bones/server/command.js:7:10)
[tilemill]     at new child (/Users/willwhite/tilemill/node_modules/backbone/backbone.js:964:41)
[tilemill]     at Plugin.start (/Users/willwhite/tilemill/node_modules/bones/server/plugin.js:136:20)
[tilemill]     at Object.exports.start (/Users/willwhite/tilemill/node_modules/bones/bones.js:28:27)
[tilemill]     at Object.<anonymous> (/Users/willwhite/tilemill/index.js:41:36)
[tilemill]     at Module._compile (module.js:456:26)
[tilemill]     at Object.Module._extensions..js (module.js:474:10)
[tilemill]     at Module.load (module.js:356:32)
[tilemill]     at Function.Module._load (module.js:312:12)
[tilemill] Started [Server Tile:20008].
[tilemill] Error: child process: "core" failed with code "8"
[tilemill] Error: child process: "tile" failed with code "143"
[tilemill] Closing child process: core (pid:46009)
[tilemill] Closing child process: tile (pid:46010)
Exiting [tilemill]
```

**Comment by springmeyer** [comment]
Thanks fixed this last night (https://github.com/mapbox/tilemill/commit/6c8a4f33b32f071ce0035f60f097e0f3a5c067f7) so it should work if you git pull latest.

**Comment by willwhite** [comment]
:+1: this works now. Thanks!
