### ISSUE TITLE
Error- getting this one consistently now when I try to open the program. Errors began when I tried to add data for tooltips

### ISSUE THREAD

**Issue by darlacameron** [mapbox/tilemill#2502]
I encountered an error:
```
[tilemill] TypeError: Cannot convert null to object
[tilemill]     at Function.<anonymous> (/Applications/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/mapnik_backend.js:358:16)
[tilemill]     at /Applications/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/lockingcache.js:72:26
[tilemill]     at Array.forEach (native)
[tilemill]     at LockingCache.<anonymous> (/Applications/TileMill.app/Contents/Resources/app/node_modules/tilelive-mapnik/lib/lockingcache.js:71:23)
[tilemill]     at process._tickDomainCallback (node.js:463:13)

```

**Comment by bsudekum** [comment]
Thanks for flagging this, looking into it.

**Comment by darlacameron** [comment]
Hi- I'm still getting the error when I try to update this map. Any word on a solution? Thanks!
