### ISSUE TITLE
tilemill/node_modules/tilelive/lib/statistics.js ERROR

### ISSUE THREAD

**Issue by obaib** [mapbox/tilemill#2511]
I get this error when i try to execute ./index.js

 set remaining() {}, // read-only
                  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/geoblink/tilemill/node_modules/tilelive/lib/scheme.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by kjeremy** [comment]
I'm seeing this as well. :+1:

**Comment by obaib** [comment]
i think i resolved that issue installing another veraion of node

**Comment by obaib** [comment]
use nvm inatall 0.12 or nvm inatall 0.10 i dont remembet the version. and use npm instal nvm to install nvm (node version manager)

**Comment by pepijndevos** [comment]
Yes, nom gave several warnings for packages that want 0.10, you command "fixed" it.

**Comment by flemmens** [comment]
I have the same issue, my node version is 0.12.7 with Ubuntu 14.04. It runs well on another server with node 0.10.13, so it seems Tilemill is not compatible with 0.12, is it possible to fix this ?

**Comment by amaeland** [comment]
Same error here, downgrading to node 0.10.x will give errors related to ```Use of const & let in strict mode```

**Comment by waneck** [comment]
@amaeland Got the same problem. Very annoying. I had to download the windows build, install it and get the `qs` module from it to replace with the version `npm` installs.
On a modern linux distro, this gets even more annoying since the node version that gets installed is more recent.
