### ISSUE TITLE
`SyntaxError: Use of const in strict mode` on startup

### ISSUE THREAD

**Issue by salomvary** [mapbox/tilemill#2541]
Node version `v0.10.31`
Npm version `1.4.23`

```
$ node ./index.js 

node_modules/connect/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (node_modules/connect/lib/middleware/bodyParser.js:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by benboughton1** [comment]
Same problem. Ubuntu 14.04.
nodejs v0.10.25
npm 1.3.10

**Comment by benboughton1** [comment]
Solution is install qs 5.2
After regular install:
cd .../node_modules/connect
npm uninstall qs
npm install qs@5.2

**Comment by florianf** [comment]
Hi folks,
I forked TileMill to work with Node v4, tested on Linux Mint 17.3 and Ubuntu 16.04 Alpha: 
https://github.com/florianf/tileoven
Most of the work was done by Paulo Viera in his fork: https://github.com/paulovieira/hapi-tilemill, maybe this works for you too!

Regards,
Florian

**Comment by tmcw** [comment]
@florianf we can give you push access to this repo - it's not necessary to fork, unless you want to.

**Comment by florianf** [comment]
@tmcw thank's for the offer, but I'll stick with the fork. With my limited knowledge and resources I only can support a basic use-case (Linux, server mode, no prebuild packages) - I think people expect more from an "official" TileMill project.
Also a huge thank you to MapBox for all the provided OSS!

**Comment by paulovieira** [comment]
@tmcw I can send a few pull requests with the necessary changes to make Tilemill work again (or give me push access and I'll send the commits). 

I've been using a customized version of Tilemill in a project in my work - [hapi-tilemill](https://github.com/paulovieira/hapi-tilemill). It would be a good way to contribute back. I had to do a little but of patching here and there, but it is relatively fresh in  my memory.

**Comment by d2lam** [comment]
Got the same problem. Switching to node v4.2.2 solved the issue for me. 
` nvm install v4.2.2`

Maybe newer versions would work too. I haven't tried.

**Comment by Komzpa** [comment]
@paulovieira pull requests would be awesome! just pull requesting from hapi-tilemill shows too much change - could you please get the required changes done without moving the whole project away? thanks! :)

**Comment by yvemalongo** [comment]
Good morning all ,
I need help I work on tillmill, I created my tile in mbtiles format but to extract it in command prompt I had to enter the command below in cmd:
C: \ Programs (x86) \ pytho38 \ python.exe C: Program Files \ mbutil-master D: \ philadelphia \ phyladelphiebasemap.mbtiles D: \ philadelphia \ philadelphia2
unsuccessful is there another alternative to extract my tiles in mbtiles

**Comment by csytsma** [comment]
Hi, are you not able to Export the MBTiles from the Tilemill browser window, under the Export dropdown?

**Comment by yvemalongo** [comment]
yes i have already exported the mbtile file now so it remains now to extract the layers in several thumbnails

**Comment by csytsma** [comment]
Tilemill has no feature to extract images from a MBTile file.  I'd suggest using a Sqlite db app, like DB Browser for Sqlite, to export the images.

Alternatively, if you just want static image files, export from Tilemill directly as a png, jpg or pdf file. No need to start with a MBTile. That's probably the easiest.
